### ISSUE TITLE
コンパイル周りの修正

### ISSUE THREAD

**Issue by ma8ma** [ma8ma/JD#8]
**edit(2019-01-09):** リストを更新

* [x] コンパイル時警告を修正する。(gcc 7 & clang 6.0) (fixed by #9 and into `test` by yama-natuki#18)
* [x] clangを使ってビルドできるように調整する (fixed by #9)
* [x] コンパイルの警告オプション ~~`-pedantic-errors`~~ `-pedantic`を追加する (fixed by #9 and into `test` by yama-natuki#20, yama-natuki#21 )
* [x] コンパイルの警告オプション(`-Wextra`など)を追加して試してみる (fixed by #13 and into `test` by yama-natuki#23 )
* [x] 保守性を高めるためオーバーライドした仮想関数に`override`を付ける (fixed by #13 and into `test` by yama-natuki#22 )
* [ ] ~~moveの妨げになっているので関数の戻り値のconst指定を外す(参照とポインタは除く)~~
  最適化するための変更は別のissueで取り扱う

gtkmm-2.4のヘッダーでwarningが出たので`-Werror`の指定は難しい。

**Comment by ma8ma** [comment]
#9 を`gtk3-preview`にマージしました。

**Comment by ma8ma** [comment]
警告オプション`-Wextra`で有効になる`-Wunused-parameter`はいくつか修正方法がありインタフェースの変更も考えられるため、今の段階では修正せずに警告オプションを暫定的に無効にします。(`-Wno-unused-parameter`を指定)

### 修正方法の案
* インタフェースを変更し引数を削除する
   ```cpp
   void foo() {} // 呼び出し側のコードも影響を受ける
   ```
* 仮引数を削除またはコメントアウトする
   ```cpp
   void foo(int) {} // 関数の情報が脱落する
   void foo(int /*hoge*/) {} // ツールやシンタックスハイライトと相性が悪いかもしれない
   ```
* unused属性をつける
   ```cpp
   void foo([[gnu::unused]] int hoge) {}  // 標準の[[maybe_unused]]はC++17なので使えない
   ```
* `void`にキャストまたは空の関数に渡す
   ```cpp
   void foo(int hoge) { static_cast<void>(hoge); } // 複数あると著しく冗長になる
   void foo(int hoge, int fuga) { unused(hoge, fuga); } // voidキャストよりはマシだが冗長
   ```

**Comment by ma8ma** [comment]
リストに挙げた修正内容について`test`ブランチへのマージリクエストを完了しました。GTK3サポートPRを準備しつつ様子を見る予定です。
